### ISSUE TITLE
Cannot read property 'point' of undefined.

### ISSUE THREAD

**Issue by pentacular** [w8r/martinez#100]
Union in some cases produces

  TypeError {
    message: 'Cannot read property \'point\' of undefined',
  }

  nextPos (algorithm/node_modules/martinez-polygon-clipping/src/connect_edges.js:78:31)
  connectEdges (algorithm/node_modules/martinez-polygon-clipping/src/connect_edges.js:142:13)
  boolean (algorithm/node_modules/martinez-polygon-clipping/src/index.js:76:18)
  union (algorithm/node_modules/martinez-polygon-clipping/index.js:10:10)

-- example follows --

union(
      [[[-12.5,0,0],[-12.259880065917969,-2.438620090484619,0],[-11.548500061035156,-4.7835001945495605,0],[-12.5,0,0]]],
      [[[-11.548500061035156,4.7835001945495605,0],[-12.259880065917969,2.438620090484619,0],[-12.5,0,0],[-11.548500061035156,4.7835001945495605,0]],
       [[-12.5,0,0],[-11.548500061035156,-4.7835001945495605,0],[12.259880065917969,-2.438620090484619,0],[-12.5,0,0]],
       [[-11.548500061035156,4.7835001945495605,0],[-12.5,0,0],[12.259880065917969,-2.438620090484619,0],[-11.548500061035156,4.7835001945495605,0]],
       [[11.548199653625488,-4.784060001373291,0],[11.548500061035156,-4.7835001945495605,0],[12.259880065917969,-2.438620090484619,0],[12.25918960571289,-2.440279960632324,0],[11.548199653625488,-4.784060001373291,0]],
       [[12.25918960571289,-2.440279960632324,0],[12.259880065917969,-2.438620090484619,0],[12.259539604187012,-2.4391300678253174,0],[12.25918960571289,-2.440279960632324,0]],
       [[12.259539604187012,-2.4391300678253174,0],[12.259880065917969,-2.438620090484619,0],[12.259650230407715,-2.438770055770874,0],[12.259539604187012,-2.4391300678253174,0]],
       [[12.259650230407715,-2.438770055770874,0],[12.259880065917969,-2.438620090484619,0],[12.259679794311523,-2.438659906387329,0],[12.259650230407715,-2.438770055770874,0]],
       [[12.259969711303711,2.4377200603485107,0],[12.259880065917969,2.438620090484619,0],[12.259679794311523,2.438659906387329,0],[12.259969711303711,2.4377200603485107,0]],
       [[12.259880065917969,2.438620090484619,0],[11.548500061035156,4.7835001945495605,0],[11.548199653625488,4.784060001373291,0],[12.25918960571289,2.440279960632324,0],[12.259880065917969,2.438620090484619,0]],
       [[12.259880065917969,2.438620090484619,0],[12.25918960571289,2.440279960632324,0],[12.259539604187012,2.4391300678253174,0],[12.259880065917969,2.438620090484619,0]],
       [[12.259679794311523,2.438659906387329,0],[12.259880065917969,2.438620090484619,0],[12.259539604187012,2.4391300678253174,0],[12.259679794311523,2.438659906387329,0]],
       [[12.259880065917969,-2.438620090484619,0],[12.259969711303711,-2.4377200603485107,0],[12.259719848632812,-2.4385499954223633,0],[12.259880065917969,-2.438620090484619,0]],
       [[-11.548500061035156,-4.7835001945495605,0],[-11.548199653625488,-4.784060001373291,0],[-11.548370361328125,-4.783490180969238,0],[-11.548500061035156,-4.7835001945495605,0]],
       [[-11.548500061035156,4.7835001945495605,0],[-11.548379898071289,4.7834601402282715,0],[-11.548199653625488,4.784060001373291,0],[-11.548500061035156,4.7835001945495605,0]],
       [[10.83080005645752,-6.12624979019165,0],[11.548199653625488,-4.784060001373291,0],[11.548370361328125,-4.783490180969238,0],[10.830659866333008,-6.12624979019165,0],[10.83080005645752,-6.12624979019165,0]],
       [[11.889439582824707,-3.659140110015869,0],[12.25918960571289,-2.440279960632324,0],[11.889439582824707,-3.332900047302246,0],[11.889439582824707,-3.659140110015869,0]],
       [[12.5,0,0],[12.259969711303711,2.4377200603485107,0],[12.259679794311523,2.438659906387329,0],[11.141039848327637,2.66117000579834,0],[11.141039848327637,0.4122300148010254,0],[12.5,0,0]],
       [[11.548199653625488,4.784060001373291,0],[11.141039848327637,5.545810222625732,0],[11.141039848327637,5.545559883117676,0],[11.548370361328125,4.783490180969238,0],[11.548199653625488,4.784060001373291,0]],
       [[11.141039848327637,5.139659881591797,0],[12.25918960571289,2.440279960632324,0],[11.548370361328125,4.783490180969238,0],[11.141039848327637,5.545559883117676,0],[11.141039848327637,5.139659881591797,0]],
       [[12.259969711303711,-2.4377200603485107,0],[12.5,0,0],[11.141039848327637,0.4122300148010254,0],[11.141039848327637,-1.9751800298690796,0],[12.259719848632812,-2.4385499954223633,0],[12.259969711303711,-2.4377200603485107,0]],
       [[11.548370361328125,-4.783490180969238,0],[11.889439582824707,-3.659140110015869,0],[11.889439582824707,-3.332900047302246,0],[10.732370376586914,-6.12624979019165,0],[10.830659866333008,-6.12624979019165,0],[11.548370361328125,-4.783490180969238,0]],
       [[11.141039848327637,-5.139659881591797,0],[12.25918960571289,-2.440279960632324,0],[12.259539604187012,-2.4391300678253174,0],[11.141039848327637,-4.113059997558594,0],[11.141039848327637,-5.139659881591797,0]],
       [[11.141039848327637,-4.113059997558594,0],[12.259539604187012,-2.4391300678253174,0],[12.259650230407715,-2.438770055770874,0],[11.141039848327637,-3.186199903488159,0],[11.141039848327637,-4.113059997558594,0]],
       [[11.141039848327637,-3.186199903488159,0],[12.259650230407715,-2.438770055770874,0],[12.259679794311523,-2.438659906387329,0],[11.141039848327637,-2.66117000579834,0],[11.141039848327637,-3.186199903488159,0]],
       [[-11.548199653625488,-4.784060001373291,0],[-11.141039848327637,-5.545810222625732,0],[-11.141039848327637,-5.545559883117676,0],[-11.548370361328125,-4.7835001945495605,0],[-11.548199653625488,-4.784060001373291,0]],
       [[11.141039848327637,-2.66117000579834,0],[12.259679794311523,-2.438659906387329,0],[11.141039848327637,-2.548830032348633,0],[11.141039848327637,-2.66117000579834,0]],
       [[11.141039848327637,2.66117000579834,0],[10.830659866333008,2.722909927368164,0],[10.830659866333008,0.506380021572113,0],[11.141039848327637,0.4122300148010254,0],[11.141039848327637,2.66117000579834,0]],
       [[-11.141039848327637,5.545810222625732,0],[-11.548199653625488,4.784060001373291,0],[-11.548370361328125,4.7835001945495605,0],[-11.141039848327637,5.545559883117676,0],[-11.141039848327637,5.545810222625732,0]],
       [[12.259710311889648,-2.438570022583008,0],[11.141039848327637,-1.9752000570297241,0],[11.141039848327637,-2.0992300510406494,0],[12.259710311889648,-2.438570022583008,0]],
       [[10.830659866333008,5.888959884643555,0],[11.141039848327637,5.139659881591797,0],[11.141039848327637,5.545559883117676,0],[10.830659866333008,6.12624979019165,0],[10.830659866333008,5.888959884643555,0]],
       [[12.25918960571289,2.440279960632324,0],[11.141039848327637,5.139659881591797,0],[11.141039848327637,4.113059997558594,0],[12.259539604187012,2.4391300678253174,0],[12.25918960571289,2.440279960632324,0]],
       [[12.259679794311523,2.438659906387329,0],[12.259539604187012,2.4391300678253174,0],[11.141039848327637,4.113059997558594,0],[11.141039848327637,2.66117000579834,0],[12.259679794311523,2.438659906387329,0]],
       [[11.141039848327637,0.4122300148010254,0],[10.830659866333008,0.506380021572113,0],[10.830659866333008,-1.846619963645935,0],[11.141039848327637,-1.9751800298690796,0],[11.141039848327637,0.4122300148010254,0]],
       [[10.830659866333008,-5.888959884643555,0],[11.141039848327637,-5.139659881591797,0],[11.141039848327637,-4.113059997558594,0],[10.830659866333008,-4.577569961547852,0],[10.830659866333008,-5.888959884643555,0]],
       [[10.830659866333008,-4.577569961547852,0],[11.141039848327637,-4.113059997558594,0],[11.141039848327637,-3.186199903488159,0],[10.830659866333008,-3.393589973449707,0],[10.830659866333008,-4.577569961547852,0]],
       [[10.830659866333008,-3.393589973449707,0],[11.141039848327637,-3.186199903488159,0],[11.141039848327637,-2.66117000579834,0],[10.830659866333008,-2.722909927368164,0],[10.830659866333008,-3.393589973449707,0]],
       [[-11.141039848327637,-4.743370056152344,0],[-11.548370361328125,-4.783490180969238,0],[-11.141039848327637,-5.5455498695373535,0],[-11.141039848327637,-4.743370056152344,0]],
       [[10.830659866333008,2.722909927368164,0],[-6.279160022735596,6.12624979019165,0],[-7.695549964904785,6.12624979019165,0],[10.830659866333008,0.506380021572113,0],[10.830659866333008,2.722909927368164,0]],
       [[-10.83080005645752,6.12624979019165,0],[-11.141039848327637,5.545810222625732,0],[-11.141039848327637,5.545559883117676,0],[-10.830659866333008,6.12624979019165,0],[-10.83080005645752,6.12624979019165,0]],
       [[-11.141039848327637,5.545559883117676,0],[-11.548370361328125,4.7835001945495605,0],[-11.141039848327637,4.659939765930176,0],[-11.141039848327637,5.545559883117676,0]],
       [[11.141039848327637,5.545810222625732,0],[11.078660011291504,5.662519931793213,0],[11.078660011291504,5.6622700691223145,0],[11.141039848327637,5.545559883117676,0],[11.141039848327637,5.545810222625732,0]],
       [[10.732370376586914,6.12624979019165,0],[10.830659866333008,5.888959884643555,0],[10.830659866333008,6.12624979019165,0],[10.732370376586914,6.12624979019165,0]],
       [[11.141039848327637,5.139659881591797,0],[10.830659866333008,5.888959884643555,0],[10.830659866333008,4.577569961547852,0],[11.141039848327637,4.113059997558594,0],[11.141039848327637,5.139659881591797,0]],
       [[11.141039848327637,4.113059997558594,0],[10.830659866333008,4.577569961547852,0],[10.830659866333008,2.722909927368164,0],[11.141039848327637,2.66117000579834,0],[11.141039848327637,4.113059997558594,0]],
       [[10.830659866333008,0.506380021572113,0],[-7.695580005645752,6.12624979019165,0],[-8.417630195617676,6.12624979019165,0],[10.830659866333008,-1.846619963645935,0],[10.830659866333008,0.506380021572113,0]],
       [[9.795860290527344,-6.12624979019165,0],[10.830659866333008,-4.577569961547852,0],[10.830659866333008,-3.393589973449707,0],[6.740960121154785,-6.12624979019165,0],[9.795860290527344,-6.12624979019165,0]],
       [[6.740960121154785,-6.12624979019165,0],[10.830659866333008,-3.393589973449707,0],[10.830659866333008,-2.722909927368164,0],[-6.279160022735596,-6.12624979019165,0],[6.740960121154785,-6.12624979019165,0]],
       [[-11.141039848327637,-5.545810222625732,0],[-11.078660011291504,-5.662519931793213,0],[-11.078660011291504,-5.6622700691223145,0],[-11.141039848327637,-5.545559883117676,0],[-11.141039848327637,-5.545810222625732,0]],
       [[10.830659866333008,-2.722909927368164,0],[11.141039848327637,-2.66117000579834,0],[11.141039848327637,-2.548830032348633,0],[10.830659866333008,-2.579400062561035,0],[10.830659866333008,-2.722909927368164,0]],
       [[11.141039848327637,-1.9752000570297241,0],[10.830659866333008,-1.8466399908065796,0],[10.830659866333008,-2.005079984664917,0],[11.141039848327637,-2.0992300510406494,0],[11.141039848327637,-1.9752000570297241,0]],
       [[11.078660011291504,5.662519931793213,0],[10.830789566040039,6.12624979019165,0],[10.830659866333008,6.12624979019165,0],[11.078660011291504,5.6622700691223145,0],[11.078660011291504,5.662519931793213,0]],
       [[10.830659866333008,5.888959884643555,0],[10.732370376586914,6.12624979019165,0],[9.795860290527344,6.12624979019165,0],[10.830659866333008,4.577569961547852,0],[10.830659866333008,5.888959884643555,0]],
       [[10.830659866333008,4.577569961547852,0],[9.795860290527344,6.12624979019165,0],[-6.278890132904053,6.12624979019165,0],[10.830659866333008,2.722909927368164,0],[10.830659866333008,4.577569961547852,0]],
       [[-11.078660011291504,-5.662519931793213,0],[-10.830789566040039,-6.12624979019165,0],[-10.830659866333008,-6.12624979019165,0],[-11.078660011291504,-5.6622700691223145,0],[-11.078660011291504,-5.662519931793213,0]],
       [[-10.830659866333008,-4.712800025939941,0],[-11.141039848327637,-4.743370056152344,0],[-11.141039848327637,-5.5455498695373535,0],[-10.830659866333008,-6.126239776611328,0],[-10.830659866333008,-4.712800025939941,0]],
       [[10.830659866333008,-1.8466399908065796,0],[-8.41765022277832,6.12624979019165,0],[-10.830659866333008,6.12624979019165,0],[-11.141039848327637,5.545559883117676,0],[-11.141039848327637,4.659939765930176,0],[10.830659866333008,-2.005079984664917,0],[10.830659866333008,-1.8466399908065796,0]],
       [[-6.279160022735596,-6.12624979019165,0],[10.830659866333008,-2.722909927368164,0],[10.830659866333008,-2.579400062561035,0],[-10.830659866333008,-4.712800025939941,0],[-10.830659866333008,-6.126239776611328,0],[-6.279160022735596,-6.12624979019165,0]]])

**Comment by rowanwins** [comment]
This now doesn't through an error on master, although I've got no idea what the output is supposed to look like, seems like a pretty crazy input

**Comment by pentacular** [comment]
Thanks for checking it out -- and I'm glad it no-longer produces an error.

I've since moved to using 'clipper-lib' for 2d booleans, largely because I now need to be able to clip open paths.

So, please feel free to close this issue if there is no further interest from your end. :)
