### ISSUE TITLE
Problems with polygon clipping (intersection)

### ISSUE THREAD

**Issue by Andi-Lo** [w8r/martinez#11]
Hey there, I am not sure if this is a duplicate of the other issues or if it is related in any form. Also I tried to use another library for line clipping (mapbox/lineclip) where I also have this kind of issue. I am not sure how to solve it.

I am currently on a project where we want to visualize ship routes. For doing that we want to clip a world map containing all coastlines by a bounding box (depending on the envelope of the route). Sadly we get strange results by the algorithm. E.g. like this is the clipped output that occurs (just) sometimes:

![image](https://cloud.githubusercontent.com/assets/7545568/21931017/671d3842-d999-11e6-8ada-caa3e58db454.png)

So the out coming polygon already has that false points in the featureCollection
And when we want to draw it (iterating over all features of the featureCollection) we get this kind of result:

![image](https://cloud.githubusercontent.com/assets/7545568/21931039/8ddbdfb0-d999-11e6-8e54-b73494d65588.png)

I tried your demo and it also seems that there are sometimes cases where the clipping (intersection method) does not produce the correct results. See this picture for example:

![image](https://cloud.githubusercontent.com/assets/7545568/21992563/390d19b0-dc17-11e6-9232-df6f36f6bb1e.png)

It seems there is some problem in the algorithm :(
I also posted this issue in the mapbox/lineclip repository: https://github.com/mapbox/lineclip/issues/1
Maybe you're internally using the lineclip library?

For any sort of help you would help our routing project big times!

**Comment by kevinkl** [comment]
Hey, I am a member of the project team of "Andi-Lo". I just want to add a screenshot that I took.
The points 1-6 are the first coordinates that we got from the mapbox/lineclip function. After point 6 the normal coastline coordinats are starting.

![clipping_bug_points](https://cloud.githubusercontent.com/assets/8057988/21994694/59494dc0-dc21-11e6-995f-a2b886d05231.png)

Thanks for all the help you can give us!

**Comment by mandysimon88** [comment]
Kevin,
The main developer on this has said he just moved to a new country and doesn’t have time to fix these problems… If you want to take a stab at digging through the code and open a pull request to fix the issues, that would be awesome. :-)

But given the large number of test cases already posted is #issues as failing, I’m not sure that adding more failing test cases as open issues will necessarily result in a quick fix.
:-)
Amanda

**Comment by w8r** [comment]
I will fix it as soon as I have a day or two to dig into it. I don't understand the connection between this algorithm and polyclip, polyclip should work nicely with bounding boxes, since it is a completely different algorithm
