### ISSUE TITLE
Edges of the same polygon overlap

### ISSUE THREAD

**Issue by AlgoTrader** [w8r/martinez#12]
![image](https://cloud.githubusercontent.com/assets/1556262/22114626/3bb3c3ba-de7b-11e6-8d4a-b0859bf4eaf5.png)

Can you please explain it?

**Comment by w8r** [comment]
A bug in the algorithm picked a wrong pair of segments to compare and decided, a full overlap occurred.

**Comment by AlgoTrader** [comment]
![image](https://cloud.githubusercontent.com/assets/1556262/22115034/84029050-de7c-11e6-99ea-451a4f3d1643.png)

**Comment by AlgoTrader** [comment]
`[ [ [ 37.51393, 55.75842 ], [ 37.51567, 55.75909 ], [ 37.51663, 55.75946 ], [ 37.51927, 55.76047 ], [ 37.51993, 55.76072 ], [ 37.52038, 55.7609 ], [ 37.52097, 55.76112 ], [ 37.52117, 55.76124 ], [ 37.52152, 55.76137 ], [ 37.52159, 55.76139 ], [ 37.52166, 55.76142 ], [ 37.52173, 55.76144 ], [ 37.5218, 55.76146 ], [ 37.52187, 55.76149 ], [ 37.52194, 55.76151 ], [ 37.52256, 55.76169 ], [ 37.52429, 55.75985 ], [ 37.52439, 55.75988 ], [ 37.52507, 55.76011 ], [ 37.52561, 55.76049 ], [ 37.52642, 55.76092 ], [ 37.52678, 55.76108 ], [ 37.52688, 55.76114 ], [ 37.52834, 55.76176 ], [ 37.52885, 55.76198 ], [ 37.53182, 55.76322 ], [ 37.53212, 55.76337 ], [ 37.53228, 55.76348 ], [ 37.53311, 55.76436 ], [ 37.53358, 55.76471 ], [ 37.53386, 55.76488 ], [ 37.53415, 55.7651 ], [ 37.53429, 55.76539 ], [ 37.53462, 55.7659 ], [ 37.53466, 55.766 ], [ 37.53473, 55.7662 ], [ 37.53606, 55.7661 ], [ 37.53624, 55.76738 ], [ 37.53663, 55.76907 ], [ 37.53728, 55.76971 ], [ 37.53792, 55.77037 ], [ 37.53896, 55.77113 ], [ 37.54057, 55.77195 ], [ 37.54186, 55.77241 ], [ 37.5434, 55.77279 ], [ 37.54443, 55.77299 ], [ 37.54634, 55.77315 ], [ 37.54808, 55.77311 ], [ 37.55192, 55.77341 ], [ 37.55551, 55.77384 ], [ 37.55917, 55.77422 ], [ 37.56692, 55.775 ], [ 37.57108, 55.77543 ], [ 37.57312, 55.77547 ], [ 37.57369, 55.77548 ], [ 37.57523, 55.77552 ], [ 37.57622, 55.77375 ], [ 37.57641, 55.77378 ], [ 37.57704, 55.77322 ], [ 37.57711, 55.77316 ], [ 37.57851, 55.77365 ], [ 37.57868, 55.77371 ], [ 37.5789, 55.77378 ], [ 37.57915, 55.77387 ], [ 37.57992, 55.77413 ], [ 37.58105, 55.7745 ], [ 37.58305, 55.77514 ], [ 37.58319, 55.77519 ], [ 37.58322, 55.7752 ], [ 37.58325, 55.77522 ], [ 37.58327, 55.77524 ], [ 37.58329, 55.77525 ], [ 37.58334, 55.7753 ], [ 37.58334, 55.77527 ], [ 37.58335, 55.77524 ], [ 37.58337, 55.77522 ], [ 37.58339, 55.77519 ], [ 37.58342, 55.77517 ], [ 37.58345, 55.77515 ], [ 37.58352, 55.7751 ], [ 37.58376, 55.77496 ], [ 37.58411, 55.77475 ], [ 37.5845, 55.77452 ], [ 37.58495, 55.77426 ], [ 37.58567, 55.77383 ], [ 37.58619, 55.77353 ], [ 37.58633, 55.77345 ], [ 37.58654, 55.77333 ], [ 37.5869, 55.77312 ], [ 37.58708, 55.77302 ], [ 37.58717, 55.77296 ], [ 37.58733, 55.77287 ], [ 37.58767, 55.77268 ], [ 37.58782, 55.77259 ], [ 37.58811, 55.77242 ], [ 37.58818, 55.77239 ], [ 37.5882, 55.77237 ], [ 37.58857, 55.77215 ], [ 37.58872, 55.77207 ], [ 37.58884, 55.772 ], [ 37.58982, 55.77143 ], [ 37.58996, 55.77135 ], [ 37.59011, 55.77126 ], [ 37.59046, 55.77106 ], [ 37.5914, 55.77052 ], [ 37.59201, 55.77015 ], [ 37.59214, 55.77009 ], [ 37.59225, 55.77003 ], [ 37.59279, 55.7697 ], [ 37.5932, 55.76947 ], [ 37.59366, 55.76919 ], [ 37.59385, 55.76908 ], [ 37.59397, 55.769 ], [ 37.59413, 55.76891 ], [ 37.59426, 55.76883 ], [ 37.59434, 55.76878 ], [ 37.59436, 55.76877 ], [ 37.59437, 55.76875 ], [ 37.59437, 55.76874 ], [ 37.59437, 55.76872 ], [ 37.59437, 55.7687 ], [ 37.59437, 55.76869 ], [ 37.59436, 55.76867 ], [ 37.59435, 55.76865 ], [ 37.59488, 55.76825 ], [ 37.59543, 55.76792 ], [ 37.59578, 55.7681 ], [ 37.59621, 55.76783 ], [ 37.59659, 55.7676 ], [ 37.59623, 55.76738 ], [ 37.59572, 55.76709 ], [ 37.59575, 55.76706 ], [ 37.59522, 55.76686 ], [ 37.59547, 55.76667 ], [ 37.59541, 55.76662 ], [ 37.59559, 55.76649 ], [ 37.59583, 55.76642 ], [ 37.596, 55.76631 ], [ 37.59621, 55.76616 ], [ 37.59676, 55.76579 ], [ 37.59707, 55.76558 ], [ 37.59805, 55.76491 ], [ 37.59835, 55.76472 ], [ 37.59877, 55.76444 ], [ 37.59899, 55.76429 ], [ 37.60055, 55.76487 ], [ 37.60062, 55.76488 ], [ 37.60067, 55.76486 ], [ 37.60111, 55.76465 ], [ 37.60135, 55.76455 ], [ 37.60184, 55.76431 ], [ 37.60203, 55.76421 ], [ 37.60251, 55.76398 ], [ 37.60262, 55.76393 ], [ 37.60271, 55.76389 ], [ 37.60335, 55.76358 ], [ 37.60351, 55.76351 ], [ 37.60424, 55.7632 ], [ 37.60371, 55.76264 ], [ 37.60444, 55.76243 ], [ 37.60452, 55.7625 ], [ 37.60495, 55.76217 ], [ 37.60511, 55.76205 ], [ 37.60534, 55.76187 ], [ 37.60539, 55.76182 ], [ 37.606, 55.76142 ], [ 37.60613, 55.76132 ], [ 37.60621, 55.76127 ], [ 37.60611, 55.7612 ], [ 37.60605, 55.76116 ], [ 37.60586, 55.76103 ], [ 37.60564, 55.76089 ], [ 37.60564, 55.76089 ], [ 37.6057, 55.76085 ], [ 37.60594, 55.76074 ], [ 37.60595, 55.76067 ], [ 37.60661, 55.76038 ], [ 37.60662, 55.76038 ], [ 37.6067, 55.76044 ], [ 37.60678, 55.76053 ], [ 37.60694, 55.76045 ], [ 37.60695, 55.76045 ], [ 37.60714, 55.76033 ], [ 37.60749, 55.76013 ], [ 37.60757, 55.76009 ], [ 37.60764, 55.76004 ], [ 37.60778, 55.75995 ], [ 37.60806, 55.75975 ], [ 37.60898, 55.75907 ], [ 37.60947, 55.75861 ], [ 37.60927, 55.7585 ], [ 37.60967, 55.75829 ], [ 37.60967, 55.75827 ], [ 37.60941, 55.7581 ], [ 37.60908, 55.75788 ], [ 37.60894, 55.75779 ], [ 37.6088, 55.75769 ], [ 37.60841, 55.75737 ], [ 37.60807, 55.75709 ], [ 37.6075, 55.75663 ], [ 37.60725, 55.75642 ], [ 37.60712, 55.75632 ], [ 37.60704, 55.75625 ], [ 37.60725, 55.7562 ], [ 37.60733, 55.75617 ], [ 37.6074, 55.75615 ], [ 37.60734, 55.75608 ], [ 37.60689, 55.7556 ], [ 37.60682, 55.75552 ], [ 37.6066, 55.75524 ], [ 37.60652, 55.75509 ], [ 37.60638, 55.7548 ], [ 37.60635, 55.75475 ], [ 37.60622, 55.75449 ], [ 37.60619, 55.75442 ], [ 37.60613, 55.75428 ], [ 37.60608, 55.75417 ], [ 37.60607, 55.75416 ], [ 37.60602, 55.75403 ], [ 37.6059, 55.75405 ], [ 37.60547, 55.75409 ], [ 37.60521, 55.75412 ], [ 37.60508, 55.75413 ], [ 37.60457, 55.75418 ], [ 37.60424, 55.75422 ], [ 37.60377, 55.75416 ], [ 37.60359, 55.75411 ], [ 37.60345, 55.75407 ], [ 37.60311, 55.75396 ], [ 37.60281, 55.75383 ], [ 37.60269, 55.75377 ], [ 37.6026, 55.75372 ], [ 37.60248, 55.75365 ], [ 37.60237, 55.75359 ], [ 37.60234, 55.75372 ], [ 37.60233, 55.75376 ], [ 37.60232, 55.75379 ], [ 37.60131, 55.75375 ], [ 37.60029, 55.754 ], [ 37.59943, 55.75404 ], [ 37.59918, 55.75427 ], [ 37.59779, 55.75453 ], [ 37.59722, 55.75467 ], [ 37.59696, 55.75474 ], [ 37.59308, 55.75579 ], [ 37.5896, 55.7567 ], [ 37.58931, 55.75644 ], [ 37.58926, 55.7564 ], [ 37.58826, 55.75679 ], [ 37.588, 55.7569 ], [ 37.58715, 55.75724 ], [ 37.58629, 55.75758 ], [ 37.58626, 55.75759 ], [ 37.58534, 55.75793 ], [ 37.58524, 55.75798 ], [ 37.58504, 55.75806 ], [ 37.58446, 55.75811 ], [ 37.58439, 55.75786 ], [ 37.58435, 55.75765 ], [ 37.5843, 55.75741 ], [ 37.58427, 55.75724 ], [ 37.58404, 55.75608 ], [ 37.58386, 55.7552 ], [ 37.58338, 55.75523 ], [ 37.58321, 55.75523 ], [ 37.58063, 55.75521 ], [ 37.57941, 55.7552 ], [ 37.57859, 55.7552 ], [ 37.57738, 55.75518 ], [ 37.57717, 55.75518 ], [ 37.57692, 55.7552 ], [ 37.57681, 55.75521 ], [ 37.57662, 55.75499 ], [ 37.57651, 55.75487 ], [ 37.57628, 55.75463 ], [ 37.57505, 55.75335 ], [ 37.57396, 55.75256 ], [ 37.57206, 55.75202 ], [ 37.5708, 55.75273 ], [ 37.56788, 55.75336 ], [ 37.56402, 55.7536 ], [ 37.56018, 55.75308 ], [ 37.55756, 55.75239 ], [ 37.55454, 55.75144 ], [ 37.54904, 55.74898 ], [ 37.54355, 55.74652 ], [ 37.54037, 55.74546 ], [ 37.53673, 55.74464 ], [ 37.5324, 55.7444 ], [ 37.52797, 55.74461 ], [ 37.52557, 55.74534 ], [ 37.52364, 55.74633 ], [ 37.52252, 55.74721 ], [ 37.52205, 55.74758 ], [ 37.52036, 55.74985 ], [ 37.52023, 55.75002 ], [ 37.5185, 55.75258 ], [ 37.51814, 55.75321 ], [ 37.51767, 55.75464 ], [ 37.5163, 55.75683 ], [ 37.51454, 55.75809 ], [ 37.51393, 55.75842 ] ] ]`

**Comment by w8r** [comment]
Is it on polygon?

**Comment by AlgoTrader** [comment]
Intersection (red color) is certainly strange

![image](https://cloud.githubusercontent.com/assets/1556262/22115359/b401072c-de7d-11e6-8beb-0dd787241e28.png)

**Comment by w8r** [comment]
I know, all the rest of the issues in this repository are about the same problem

**Comment by AlgoTrader** [comment]
Well, are there any chances we can fix it?

**Comment by w8r** [comment]
There are solid chances to fix it, I explained the approach in #8, I just cannot do it right now or next week, since I am really busy. I am sorry if it is urgent for you, I am doing my best

**Comment by w8r** [comment]
here's the testcase: https://codepen.io/w8r/pen/MrebNZ?editors=0010 
it's collapsed edges in 1 polygon (2 points overlapping)

**Comment by w8r** [comment]
I decided for now to get rid of the collapsed edges. #42
