### ISSUE TITLE
Wrong result for a basic diff 

### ISSUE THREAD

**Issue by jmtrivial** [w8r/martinez#124]
Dear w8r,

Thank you for your tool, it's very easy to use, I recently discovered it while I was developping [svg-to-stl](https://github.com/jmtrivial/svg-to-stl).

I found a bug I didn't yet explored, but with a very basic configuration : two rectangles, a small one and a large one. The small one should cut the large into two rectangles when applying a diff, but when edges are collinear, it produces incoherent shapes:

![bug](https://user-images.githubusercontent.com/346360/77700368-5a6b4f80-6fb4-11ea-804b-7d4378b817eb.png)

I think that one edge should be part of the right rectangle, but has been integrated to the left rectangle.

If I'm not wrong (I only tested this configuration in Codepen, and write this example without testing it), here is an example:
`{
  "features": [
    {
      "geometry": {
        "coordinates": [[[0,10],[0,-10],[30,-10],[30,10],[0,10]]],
        "type": "Polygon"
      },
      "properties": {},
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [[[10,10], [10,-10],[20,-10],[20,10],[10,10]]],
        "type": "Polygon"
      },
      "properties": {},
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
                [[[0,10],[0,-10],[10,-10],[10,10],[0,10]]],
                [[[20,10],[20,-10],[30,-10],[30,10],[20,10]]]
        ],
        "type": "MultiPolygon"
      },
      "properties": {"operation": "diff"},
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
`

**Comment by w8r** [comment]
I have a strong feeling it could be connected to 21re/rust-geo-booleanop/pull/15

**Comment by bluenote10** [comment]
To me it looks more related to the fixes in 21re/rust-geo-booleanop/pull/13. It works in the Rust version -- I can have a quick look.
