### ISSUE TITLE
Wrong result with basic diff

### ISSUE THREAD

**Issue by jmtrivial** [w8r/martinez#126]
Dear developers,

I've integrated #125 in my svg-to-stl software, and it fixes the bug I had.
However, I recently discovered a new error, again with a diff.

You can easily try it in the playground using the following data:

```
const data = {
  "type": "FeatureCollection",
  "features": [{
    "type": "Feature",
    "properties": {},
    "geometry": {
      "type": "Polygon",
      "coordinates": [[[100,0],[100,60],[0,60],[0,50],[80,50],[80,0],[100,00]]]
    }
  },{
    "type": "Feature",
    "properties": {},
    "geometry": {
      "type": "Polygon",
      "coordinates":
        [[[30,50],[80,50],[80,10],[100,10],[100,60],[30,60],[30,50]]]
      
    }
  }]
}
```

Here attached the result, that should be composed of two rectangles (one at the end of each part of the "L" shape).
![diff](https://user-images.githubusercontent.com/346360/79444064-f3512180-7fda-11ea-8e2b-e980315cd634.png)

**Comment by rowanwins** [comment]
This appears to be fixed v0.7.3 , I think because of this https://github.com/w8r/martinez/commit/2e49fe910e32ed31f6da240aad392361df0fe9cd
