### ISSUE TITLE
Intersection results in a self-intersection polygon that doesn't have equal first and last point

### ISSUE THREAD

**Issue by mglasgow** [w8r/martinez#127]
I am working on an app that divides up the OpenStreetMap country boundaries into [QuadTiles](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/). This involves a lot of intersections and I am discovering quite a few edge cases in martinez. A lot of these issues have been solved by forcing [turf-intersect](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect) to use the latest master code of martinez. I assume this is because of the good work that @bluenote10 has been doing recently.

For this edge case, I have created a geojson file in the handy "genericTestCase" format that @bluenote10 recently.

I expect this intersection to return two polygons. But the second polygon of the intersection result actually ends up being:
`[
      [
        [
          90.902593696155,
          80.645340246439
        ],
        [
          91.40625,
          80.645340246439
        ],
        [
          90.902593696155,
          80.645340246439
        ],
        [
          91.40625,
          80.809517148901
        ],
        [
          91.40625,
          80.645340246439
        ]
      ]
    ]`

This isn't a valid polygon, as the first and last point do not match. It also contains a self intersection, in that the first three points make a triangle and could be removed.

**Comment by mglasgow** [comment]
[issue127.geojson.txt](https://github.com/w8r/martinez/files/4567208/issue127.geojson.txt)

**Comment by bluenote10** [comment]
FYI it seems to work fine in the Rust version. Second polygon is:

```
            [
              [90.902593696155, 80.645340246439],
              [91.40625, 80.645340246439],
              [91.40625, 80.809517148901],
              [90.902593696155, 80.645340246439]
            ]
```

Most likely it is the issue I have fixed in #125 -- on the bottom the two overlapping segments are affected by the wrong order of compute fields.

![image](https://user-images.githubusercontent.com/3620703/80857502-060e5c00-8c53-11ea-970b-470b12a215d2.png)

**Comment by mglasgow** [comment]
Excellent, I was wondering if it was fixed in your Rust version. It might be a useful regression test to add to the code base anyway? I look forward to getting #125 committed.

**Comment by bluenote10** [comment]
Assuming that it is the same issue, #125 already contains the minimal regression test for that problem ;)

**Comment by mglasgow** [comment]
I've just applied your #125 fix to my local working copy and I can confirm that it fixes this issue. Thanks for your help.
