### ISSUE TITLE
Degenerate Intersection Fail

### ISSUE THREAD

**Issue by Fribur** [w8r/martinez#141]
subject: [[ [ [0,0], [4,0], [4,4], [0,4], [0, 0] ] ]] 
clipper: [[ [ [2,2], [2,0], [6,0], [6,-2], [-2,-2], [-2,-0 ], [ 2,2] ] ]] 

Issue is that splitting of edges results in inserting 2,0-->4,0 twice into the queue and sweepline. Which somehow messes up what is "inResult" and what is out. I tried preventing the second insertion into the Priority Queue in "DivideSegment", skipping the "next" node in "SubdivideSegments" when it is identical with the current node, all of which results in better looking results, but not perfect. I am out of ideas what else to try as I also do not quite understand what is done in "ComputeFields". Have a hunch it could be dealt within by some changes in "inResult" or "determineResultTransition"?

![image](https://user-images.githubusercontent.com/16464641/152626109-697ffc00-baf2-452e-b6bf-fe9936f4d804.png)

**Comment by rowanwins** [comment]
This appears to be fixed v0.7.3 , I think because of this https://github.com/w8r/martinez/commit/2e49fe910e32ed31f6da240aad392361df0fe9cd
