### ISSUE TITLE
Would this library works on bezier cuvers?

### ISSUE THREAD

**Issue by army8735** [w8r/martinez#150]
![0E00503F-9A5E-4DEB-A6E5-CF9012388981](https://user-images.githubusercontent.com/174904/165262265-0341188d-9ded-437c-9278-fd5623125c81.png)

**Comment by w8r** [comment]
Hi Army! I am afraid it wouldn't. It couldn't calculate intersections between parametric curves, and this is at the core of the algorithm. Parametric curves can be discretised into polygons though.

**Comment by z3dev** [comment]
@w8r you could calculate a set of points based on the Bézier curves, and then use the points with this library.

**Comment by army8735** [comment]
https://github.com/w8r/bezier-intersect

**Comment by z3dev** [comment]
Library wars!

https://github.com/microsoft/maker.js

**Comment by army8735** [comment]
https://mat.polsl.pl/sjpam/zeszyty/z6/Silesian_J_Pure_Appl_Math_v6_i1_str_155-176.pdf

This method could calculate points of intersections of two bezier curves.
And I have translated it into Javascript.
Maybe it is useful.

http://army8735.me/isec.js
