### ISSUE TITLE
Replace RB-tree with AVL

### ISSUE THREAD

**Issue by w8r** [w8r/martinez#17]
Reason - simpler code, less dependencies, performance (the one that is used now, though being absolutely brilliant, is not really fast)

* [w8r/avl](https://github.com/w8r/avl) what's missing now is to make sure the tree is properly iterable &rarr; `.next()` `.prev()`

**Comment by w8r** [comment]
So far the implementation is ready, but slow because of recursion, so I will tweak it first to surpass both RB-tree implementations and make a replacement

**Comment by rowanwins** [comment]
Hey @w8r ,

Looks like `avl` is now going pretty quick, would you like me to take a look at starting this incorporation?

**Comment by w8r** [comment]
Hi Rowan, thanks for your offer! Yes, sure, the last thing I have to make sure of is that the tree allows for duplicate keys, now it doesn't. I remember that it was actually the reason of failure with `js-bintrees`

**Comment by w8r** [comment]
@rowanwins I have finished the tree, I think I will have some time this week to try and put it into the code. Did you have some examples to measure the performance on? Or I can use Indonesia geojson I had

**Comment by rowanwins** [comment]
Hey @w8r 

Made a bit of a start on the replacement the other day but couldn't quite get it working so I need to take another look, although you'd probably be able to make the changes quicker than I as you understand the tree structure better than me. 

Re the performance testing I reckon the Indonesia geojson is a good candidate.

**Comment by w8r** [comment]
cool! yes, it's bit tricky there, cause the new tree is not persistent, but I think it should be fine, I will take a look. I will just try and write some benchmark code before to have something to compare it with.

**Comment by w8r** [comment]
and I remember the pain point - moving the iterators on the tree, also see *a lot* of unoptimized code there
