### ISSUE TITLE
Unnecessary exports for testing purposes  

### ISSUE THREAD

**Issue by DenisCarriere** [w8r/martinez#22]
Would be useful to remove any unnecessary exports that are used for testing purpose in the main `/index.js`.

This allows the `require()` to only returns methods that are used in the current API.

**Question:** Is `.boolean` even worth adding to the API? This just adds complexity to 4 simple methods `union`, `diff`, `xor` & `intersection`. Running these functions programmatically can easily be done on the user's side, there's no strong reason to include in the core methods.

```
$ node
> require('./')
{ union: [Function],
  diff: [Function],
  xor: [Function],
  intersection: [Function] }
```

## Current

**/index.js**
```javascript
module.exports = require('./src/index');
```

**/src/index.js**

```javascript
module.exports = boolean;

module.exports.union = function(subject, clipping) {
  return boolean(subject, clipping, UNION);
};

module.exports.diff = function(subject, clipping) {
  return boolean(subject, clipping, DIFFERENCE);
};

module.exports.xor = function(subject, clipping) {
  return boolean(subject, clipping, XOR);
};

module.exports.intersection = function(subject, clipping) {
  return boolean(subject, clipping, INTERSECTION);
};

/**
 * @enum {Number}
 */
module.exports.operations = {
  INTERSECTION: INTERSECTION,
  DIFFERENCE:   DIFFERENCE,
  UNION:        UNION,
  XOR:          XOR
};

// for testing
module.exports.fillQueue            = fillQueue;
module.exports.computeFields        = computeFields;
module.exports.subdivideSegments    = subdivideSegments;
module.exports.divideSegment        = divideSegment;
module.exports.possibleIntersection = possibleIntersection;
```

## Proposed

**/index.js**

```javascript
var martinez = require('./src/index');

module.exports = {
  union: martinez.union,
  diff: martinez.diff,
  xor: martinez.xor,
  intersection: martinez.intersection
};
```

**/src/index.js**

> Unchanged

**Comment by w8r** [comment]
Well, then the internal methods have to be moved to different files for testing.

**Comment by w8r** [comment]
I mean `subdivideSegments `, `fillQueue` etc

**Comment by DenisCarriere** [comment]
Not necessarily, at the moment all the tests are passing because they `import/require` the methods directly from `/src`.

## Example

**/test/divide_segment.test.js**

```javascript
var martinez = require('../src/');
var divideSegment = martinez.divideSegment;
```

The main change I was proposing was dropping `.boolean` from your API since this seems like it was only used for testing/internal purposes.

I'll add `.boolean` & `.operations` back to the PR since you seem to be [using it in your demo](https://github.com/w8r/martinez/blob/master/demo/js/index.js#L78-L109).

**Comment by w8r** [comment]
That's not really necessary, the constants used in the demo can be not tied to the lib. I can update the demos

**Comment by DenisCarriere** [comment]
Oh ok, currently the `require('./')` returns the following:

```javascript
$ node
> require('./')
{ [Function: boolean]
  union: [Function],
  diff: [Function],
  xor: [Function],
  intersection: [Function],
  operations: { INTERSECTION: 0, DIFFERENCE: 2, UNION: 1, XOR: 3 } }`
```

Are you fine if we drop `.operations` & the main default export (`.boolean`)?

It would look something like this:

```javascript
$ node
> require('./')
{ union: [Function],
  diff: [Function],
  xor: [Function],
  intersection: [Function] }
```

**Comment by w8r** [comment]
yes, I'm updating the demo

**Comment by w8r** [comment]
@DenisCarriere, I updated the demo and merged your commits in a different branch
