### ISSUE TITLE
Mourner ESLint config

### ISSUE THREAD

**Issue by DenisCarriere** [w8r/martinez#25]
Have you considered using [`eslint-config-mourner`](https://github.com/mourner/eslint-config-mourner)? It's very similar to your current eslint config file and you can easily include it in your [`package.json`](https://github.com/mourner/kdbush/blob/master/package.json#L19-L21) instead of defining each specific rule yourself in the `.eslintrc`.

Mourner's linter is strict when writing in ES5, however it does allow ES6 syntax for your tests (it's painful writing tests in pure ES5).

**Comment by w8r** [comment]
good point

**Comment by DenisCarriere** [comment]
👍 I'll send over a commit, shouldn't be very many changes since both linters are almost identical.

**Comment by w8r** [comment]
@DenisCarriere I really don't like the removal of vertical alignment, that's a very useful formatting technique, especially with my attention span being similar to that of a fish. Maybe I can create a fork of the eslint standard with this feature added? Though keeping that in the .eslintrc is just simpler
