### ISSUE TITLE
`connectEdges` initial numbering causes exception

### ISSUE THREAD

**Issue by w8r** [w8r/martinez#3]
Labelling step here https://github.com/w8r/martinez/blob/master/src/index.js#L446 puts `undefined` in `pos`, when the `otherEvent` is ahead of the current one in `resultEvents`

Possible solutions are: 
 * split it into two loops
 * use `indexOf()` (could be worse)

**Comment by sh1ng** [comment]
I'm not sure. Are you able to reproduce it in the real world scinarios?

**Comment by w8r** [comment]
Unfortunately)) i'll provide the test case

Kind regards,
Alexander Milevski
