### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by xaviergonz** [w8r/martinez#36]
Are there any performance benchmarks vs other libs available?

JsClipper, the javascript port of Angus Johnsons Clipper (based on Vatti´s algorithm) come to mind for example

**Comment by rowanwins** [comment]
Gday @xaviergonz 

You can see a comparison of martinez vs jsts by opening the console of the demo page, there currently isn't anything other than that. 

There is also some work being done on [performance](https://github.com/w8r/martinez/issues/17) so it would be worth running some checks once this work is done.

Cheers

**Comment by w8r** [comment]
some benchmarks against JSTS are added in #42 
still makes sense to try against JsClipper

**Comment by sheerun** [comment]
How about https://github.com/mfogel/polygon-clipping ?

**Comment by rowanwins** [comment]
Information on benchmarks can be found in the [readme](https://github.com/w8r/martinez#benchmarks) or the [benchmarks file](https://github.com/w8r/martinez/blob/master/bench.js
).

The polygon-clipping lib also has [some benchmarks](https://github.com/mfogel/polygon-clipping/blob/master/bench/bench.js) containing this lib.
