### ISSUE TITLE
Wrong result for union operation

### ISSUE THREAD

**Issue by AtiX** [w8r/martinez#4]
Hi, thanks for creating this library!

I am getting wrong results when using the union operation for this specific case:

- big rectangle (grey): `[[-25,-25],[25,-25],[25,25],[-25,25]]`
- small rectangle (red): `[[-26,-22.5],[-26,-27.5],[-15,-27.5],[-15,-22.5]]`
- union result (cyan): `[[-26,-27.5],[-15,-27.5],[-15,-25],[25,-25],[25,25],[-26,-27.5]]`

![unbenannt](https://cloud.githubusercontent.com/assets/236678/18125442/8b9ca6fe-6f76-11e6-8969-e1b5af4d2cb2.PNG)
(svg coordinates, so origin is in the center, y-plus goes downwards)

The union result has a duplicate point and is missing one point of the original input. Any thoughts, am I doing something wrong?

**Comment by w8r** [comment]
I'll build a test case for that and get back to you.

**Comment by w8r** [comment]
@AtiX, please take a look at this codepen http://codepen.io/w8r/pen/rrBkER
I put your data in the `GeoJSON` format and rendered it using Leaflet

My result is
```
result [
  [
    [
      -26,
      -27.5
    ],
    [
      -15,
      -27.5
    ],
    [
      -15,
      -25
    ],
    [
      25,
      -25
    ],
    [
      25,
      25
    ],
    [
      -25,
      25
    ],
    [
      -25,
      -22.5
    ],
    [
      -26,
      -22.5
    ],
    [
      -26,
      -27.5
    ]
  ]
]
```

**Comment by AtiX** [comment]
Thanks a lot for your work. Although the first and last point are duplicated (should that be?), the result looks fine on codepen (AND differs from my local result - so I'll have a look and try to isolate the code locally).

**Comment by w8r** [comment]
that's a `GeoJSON` spec, as far as I know and it makes sense: it makes sure that the polygon is closed, no matter how you want to render it - you can use a polyline, for instance.

**Comment by AtiX** [comment]
Thanks!
