### ISSUE TITLE
Union operation splitting the resulting polygon in two

### ISSUE THREAD

**Issue by lemilonkh** [w8r/martinez#43]
Hi, we're using your library and it's working out good so far (at least when rounding the input values onto a certain grid), but sometimes the union doesn't behave like it should. Instead, its output is multiple polygons 

I've managed to extract the relevant polygons into a CodePen [here](https://codepen.io/lemilonkh/pen/JyQwye) (use the union mode).
Here's a screenshot for a quick look:
![union_gone_wrong](https://user-images.githubusercontent.com/93539/30214648-8015ea54-94ad-11e7-958f-16ae80dd4c37.png)

Is this something you have encountered before perhaps? Thanks a lot for your help :)

**Comment by lemilonkh** [comment]
I managed to simplify the example a bit while retaining the result, see [here](https://codepen.io/lemilonkh/pen/eEwxMw). It has a lot fewer points, but shows the same behaviour. Is this related to the second polygon's edge being contained in the first polygon's edge?

**Comment by rowanwins** [comment]
Hey @lemilonkh 

Thanks for reporting the bug, we're currently in the midst of refactoring some stuff so we'll add this to the test cases and see if we can work out what's going on.

**Comment by lemilonkh** [comment]
Thanks a lot, let me know if I can help out in any way 😃
