### ISSUE TITLE
Dead code - Condition is always true

### ISSUE THREAD

**Issue by JonMcPherson** [w8r/martinez#46]
I am working on porting this to Scala and have noticed that the condition on [Line 363 of index.js](https://github.com/w8r/martinez/blob/1e6d4ae021683e62e11ee27d004990f1c7e47d4b/src/index.js#L363) is checking equality between 2 different types which will always have the same outcome.
Based on the https://github.com/mikolalysenko/functional-red-black-tree source and when debugging, `prev.node` in this context will be a `RBNode` and `sweepLine.begin` will be a `RedBlackTreeIterator`.  So this condition will always return `true` for not equal.
Additionally, what is the purpose of these 2 lines in the following else block?
```
prev.prev();
prev.next();
```
If I am just missing something here, an explanation would be appreciated. Thanks!

**Comment by JonMcPherson** [comment]
I noticed that the RB tree implementation was switched some time ago in commit 0f65cbf.  After reading the diffs, it looks like this could have just been an oversight when converting to the new implementation.

**Comment by JonMcPherson** [comment]
The tests also always evaluate this condition as true and never reach the else block.
The same goes for the the condition on [line 384](https://github.com/w8r/martinez/blob/1e6d4ae021683e62e11ee27d004990f1c7e47d4b/src/index.js#L384)

**Comment by rowanwins** [comment]
Hi @JonMcPherson 

There is a [new branch](https://github.com/w8r/martinez/tree/rowanwins-avl-again) which replaces the rb-tree implementation which should address some of the issues.

Unfortunately this code is still a bit of a work-in-progress and there have been a couple of bugs that we've never quite ironed out. It mostly works but there are some edges cases which are proving tricky to debug.

Any assistance would be greatly appreciated (esp if you happen to be a geometry algorithm genius :) )

**Comment by w8r** [comment]
So basically this one is not going to be fixed, it is already replaced in the version with the new tree, these conditions were actually eliminated. 

Maybe I should've released the version after just tree replacement, but it's too late already, we'll have to wait until the next release.

**Comment by JonMcPherson** [comment]
Thanks for the update.
I did notice the `rowanwins-avl-again` branch and have started working off that one.  
All the tests pass on that branch, so I'm wondering if there Is any additional unit tests for the broken functionality or the bugs you speak of?
I'd be happy to help out wherever I can.  I'll let you guys know if I find or fix anything while porting it.

**Comment by rowanwins** [comment]
Hi @JonMcPherson 

I'll be taking a look at this repo in a week or two once I've got some other commitments out the way. Hopefully then I'll rejig the test suite a little bit to make it a bit easier to identify the edge cases.

FYI there are a few other implementations out there
https://github.com/kudm761/martinez-rueda-php
https://github.com/voidqk/polybooljs (also contains a helpful writeup of the algorithm)
And the original c++ http://www4.ujaen.es/~fmartin/bool_op.html

Unfortunately each implementation is a bit different and so it take a while to work out what's what.

**Comment by w8r** [comment]
And you can ask me questions, I will try and help
