### ISSUE TITLE
Wrong intersection

### ISSUE THREAD

**Issue by dongli** [w8r/martinez#50]
Pictures show themselves, where the green square in the first picture is the clipping polygon, the weird polygon in the second picture is the result which doesn't looks good.
![image](https://user-images.githubusercontent.com/367959/33211605-4624436a-d15a-11e7-9001-b6b97d48624a.png)
![image](https://user-images.githubusercontent.com/367959/33211644-6fa48fc4-d15a-11e7-9a85-457b4fb1ec9a.png)
The GeoJSON files can be found [here](https://gist.github.com/dongli/6faabfd4014bd0661233e894ffc6335d).

**Comment by w8r** [comment]
Will be solved by #42

**Comment by dongli** [comment]
@w8r Thanks! I found it was caused by the multiple polygons. After I loop over each polygon, everything looks good.
