### ISSUE TITLE
Importing with webpack fails!

### ISSUE THREAD

**Issue by saintplay** [w8r/martinez#52]
Trying to use this awesome lib, but it always gives me: 
`Error: TypeError: Tree is not a constructor` Which have its origin [right here](https://github.com/w8r/martinez/blob/master/src/subdivide_segments.js#L3)

I don't know if the problem is the build process from **martinez** or **avl**,
but the workaround I found is changing the line  
`var Tree                 = require('avl');` to  
`var Tree                 = require('avl').default`;

But changing this line, also screw up the tests. **So this is a build inconsistency**

So I checked **avl** build process and I think there should be a minified UMD ES5 file.

Like I did for my [PR](https://github.com/saintplay/martinez) of this lib
My minified file has only 14.3kb(Webpack), instead of 54kb(current size)

I can't make a pull request because the test are failing, and the problem probably begins in the **avl** lib.

My suggestion is: migrate **martinez** and **avl**  build process from rollup/browserify to Webpack.

**Comment by w8r** [comment]
it's a webpack problem, not the library, but I will fix it by adding a special field to the exports. In both libraries. 
like that https://github.com/mourner/tinyqueue/blob/master/index.js#L4

**Comment by saintplay** [comment]
All right, I'll be kindly waiting then

**Comment by w8r** [comment]
please try `v0.3.1`

**Comment by saintplay** [comment]
unfortunately it doesn't
I have a sanbox here: https://www.webpackbin.com/bins/-L2Cnnyl869SDJ6E49Vb

See console error

**Comment by w8r** [comment]
`v0.3.2` fixes it. Later I will switch to es6 modules

**Comment by saintplay** [comment]
Oh great! It works well in all my environments, Thank you so much for your work!
