### ISSUE TITLE
Does not work under react16/webpack3

### ISSUE THREAD

**Issue by gap777** [w8r/martinez#53]
I know, I know... what does react16 have to do with this JS library? 
We're moving from react 15 + webpack2 -> react 16 + webpack 3. 
Martinez 0.3 works fine for us with react 15+webpack 2.
Martinez 0.3 fails under react15+webpack3. 
The exception thrown is "TypeError: Tree is not a constructor" in `subdivide_segments.js` (line 11). 
The stack trace is:
```
Uncaught TypeError: Tree is not a constructor
    at subdivide (subdivide_segments.js:11)
    at boolean (index.js:69)
    at Object../node_modules/@rms/geometry/node_modules/martinez-polygon-clipping/src/index.js.boolean.diff (index.js:84)
    ..... our code ....
```
Upon closer inspection, it appears that in this situation, the statement:
```var Tree = require('avl');```
doesn't actually give access to the Tree constructor. Look at the attached screenshot to see what the Tree variable is... looks like it's an ES6 module with `default` property, instead of the constructor itself.
Perhaps this is something I can work-around by configuring my environment? 
Open to suggestions

![screen shot 2018-01-05 at 1 58 05 pm](https://user-images.githubusercontent.com/6495610/34631517-b9cbecfa-f23e-11e7-8b4c-8e207e745f16.png)

**Comment by w8r** [comment]
please try version `0.3.1`

**Comment by gap777** [comment]
I'm thankful for the quick turn-around, w8r... but no dice. Same result. I prune my npm tree & reinstalled to make sure.

![screen shot 2018-01-06 at 5 21 19 pm](https://user-images.githubusercontent.com/6495610/34644512-120da616-f306-11e7-819e-9ba999df5880.png)

**Comment by saintplay** [comment]
I had the same problem,
I got a working PR if you are in a hurry

https://github.com/saintplay/martinez

**Comment by w8r** [comment]
@saintplay, thanks, but I don't want webpack in this project, it's an overkill.

**Comment by saintplay** [comment]
maybe changing the `require` statements to `import` and browserify for Rollup will do the job

**Comment by gap777** [comment]
@w8r, @saintplay what is your understanding of the nature of the problem?

**Comment by saintplay** [comment]
the **browserify** bundle of **martinez** is not working with Webpack3

**Comment by w8r** [comment]
v0.3.2 fixes it. Later I will switch to es6 modules
