### ISSUE TITLE
Would support LineString?

### ISSUE THREAD

**Issue by dongli** [w8r/martinez#54]
In some cases, I need to clip rivers or other line objects. Would `martinez` support it? Thanks for advice!

**Comment by JonMcPherson** [comment]
I don't think so. I've had to use the Cohen Southerland algorithm for the same use case.

**Comment by rowanwins** [comment]
As @JonMcPherson says martinez isn't really designed to deal with lines. Most of the js line clipping algorithms, eg [lineclip](https://github.com/mapbox/lineclip) and [liang-barsky](https://github.com/w8r/liang-barsky), are designed for clipping by bbox only which is somewhat limited. 

@JonMcPherson I thought Cohen-Sutherland could only clip by a bbox, do you have anything different that you can point us to?

**Comment by JonMcPherson** [comment]
@rowanwins  yea Cohen-Southerland is against a bbox only which is what I needed.  From what I've found, most well known line clipping algorithms are either against a bbox or convex polygon.

**Comment by rowanwins** [comment]
Closing as the martinez algorithm isn't suited to this task
