### ISSUE TITLE
A case where intersection is incorrect

### ISSUE THREAD

**Issue by fresidue** [w8r/martinez#6]
Hi,

I am not sure if it is due to the polygons are self-intersecting, or that the borders are overlapping, but I have a case where the intersection (as well as most of the other operations) give incorrect results.

The polygons used: 
`var p0_x = [
   [
    [0,0],
    [0,1],
    [1,0],
    [1,1],
    [0,0]
  ]
];`
`var p1_x = [
  [
    [0, 0.5],
    [0, 1.5],
    [1, 0.5],
    [1, 1.5],
    [0, 0.5]
  ]
];`

Using the [pen](http://codepen.io/fresidue/pen/ALvgxE?editors=0011) by AtiX (thx:) - 
![screen shot 2016-09-08 at 14 34 15](https://cloud.githubusercontent.com/assets/594442/18349382/7985676a-75d1-11e6-8607-35dd1ac0647a.png)

Gives an intersection -
![screen shot 2016-09-08 at 14 36 17](https://cloud.githubusercontent.com/assets/594442/18349411/aa5837fa-75d1-11e6-85e7-79f391cd097a.png)

and union - 
![screen shot 2016-09-08 at 14 37 20](https://cloud.githubusercontent.com/assets/594442/18349456/d4e6cfc2-75d1-11e6-88b6-5e45ded16552.png)

**Comment by w8r** [comment]
@fresidue, thanks! Definitely it's a bug and it's caused by overlapping edges. That's the unstable part of the algorithm that needs attention and we are going to work on it. To be more specific, there is a point in the processing when the segments are compared to decide in which direction to proceed while constructing the result geometry. Some of  the rules we introduced there, are unstable.

Thank you so much for the simple test case!

**Comment by w8r** [comment]
http://codepen.io/w8r/pen/ozpKNv

**Comment by gap777** [comment]
Any update on this? We're hitting the same issue, and need the fix in order to utilize this library in our system.

**Comment by w8r** [comment]
@gap777 Will work on it end of this week, if I'll find time. Definitely not forgotten ))

**Comment by gap777** [comment]
@w8r,

Perhaps we could assist… can you give us any ideas on which function the problem lies? We’ve been studying your code, and may be able to expedite the solution.

Thanks

@gap777

**Comment by w8r** [comment]
First, the RBTree I am using, is horrible: there are cases when I cannot retrieve stuff that I've put there. So I re-implemented these structures myself here: https://github.com/w8r/binary-trees,

Here's where the problem occurs: https://github.com/w8r/martinez/blob/master/src/index.js#L343

There are also visual debugging routines that you can uncomment. 

To me it looks as the sorting of the segment pool fails somehow and the algorithm takes a wrong direction.

**Comment by mandysimon88** [comment]
@w8r thanks for being willing to take a look at this... :-)

**Comment by gap777** [comment]
@w8r any progress on this over the weekend? We're at a standstill with the "flagpole" bug, and we'd love to make sure of the great work you've done here.

**Comment by w8r** [comment]
I started working on replacing the Tree structure, but no significant progress so far. I can switch to looking at your particular test cases, if I will have time this week

**Comment by w8r** [comment]
can you try and fiddle with your data before I fix it? like trying to add another point at a problematic place?

**Comment by gap777** [comment]
@w8r, how about we chat on skype to discuss further? It's not clear what you want me to do ('fiddle with data'). We're seeing a variety of issues:

- the "flagpole" bug (extra vertex as a result of an intersection). 
- missing vertices 
- "extra" shapes (a 2nd shape is included in the result returned from intersection(), but it's just a line with 2 vertices)

My colleague @mandysimon88 gave you test cases which should allow you to easily reproduce them. 

My skype handle is gary.passero

**Comment by mandysimon88** [comment]
@w8r, we are really sure that our test cases are correct. Sometimes the result is missing vertices, sometimes it has extra vertices, and sometimes it has an extra shape (essentially, a line of two points).

However, what is common in ALL of these cases that fail is that the original two polygons have an edge that overlaps.

So we think it is really "one" bug where overlapping edges fail. For us, this is a big deal because our program uses overlapping edges in the majority of cases.

Would it be helpful to send you more test cases, or, is the one I posted in the other Issue thread enough to get you to the root of the problem?

**Comment by w8r** [comment]
Yes please, more test cases would certainly help!

**Comment by mandysimon88** [comment]
Test case: rectangle with another rectangle, two edges overlapping:
_______________
|          |           |
|______|           |
|                      |
|______________|

[ [ 30, 78 ], [ 30, 30 ], [ 126, 30 ], [ 126, 78 ], [ 30, 78 ] ] (polygon1)
[ [ 30, 30 ], [ 55, 30 ], [ 55, 55 ], [ 30, 55 ], [ 30, 30 ] ] (polygon2)

Should return exactly the same as polygon2, but returns:
[ [ [ 30, 30 ], (correct)
    [ 55, 30 ], (correct)
    [ 55, 30 ], (duplicate)
    [ 30, 78 ], (vertex from polygon1 that is outside of polygon2)
    [ 30, 55 ], (out of order, should come second-to-last)
    [ 55, 55 ], (out of order, should come third-to-last)
    [ 30, 30 ] ] ]

**Comment by mandysimon88** [comment]
Test case: rectangle with a trapezoid, with one edge overlapping:
[ [ 0, 3.5 ], [ 0, 0 ], [ 21, 0 ], [ 21, 3.5 ], [ 0, 3.5 ] ] (rectangle)
[ [ 21, 7 ], [ 0, 7 ], [ 7, 0 ], [ 14, 0 ], [ 21, 7 ] ] (trapezoid)

Should return:
[ [ 3.5, 3.5 ], [ 7, 0 ], [ 14, 0 ], [ 17.5, 3.5 ], [ 3.5, 3.5 ] ] (== the top half of the trapezoid)

Instead returns:
[ [ [ 3.5, 3.5 ], (correct)
    [ 7, 0 ], (correct)
    [ 14, 0 ], (correct)
    [ 21, 0 ], (vertex is outside rectangle)
    [ 14, 0 ], (duplicate)
    [ 21, 3.5 ] ] ] (vertex is outside rectangle)
Missing last two vertices: [ 17.5, 3.5 ], [ 3.5, 3.5]

Warning message:
< Edges of the same polygon overlap [ 7, 0 ] [ 21, 0 ] [ 14, 0 ] [ 21, 0 ]

**Comment by mandysimon88** [comment]
Test case: rectangle with another rectangle, where they have 3 edges overlapping:
[ [ 0, 48 ], [ 0, 0 ], [ 96, 0 ], [ 96, 48 ], [ 0, 48 ] ] (rectangle1)
[ [ 0, 0 ], [ 192, 0 ], [ 192, 48 ], [ 0, 48 ], [ 0, 0 ] ] (rectangle2)

Incorrectly returns TWO shapes:
[ 
[ [ 0, 0 ],  (correct)
[ 96, 0 ], (correct)
[ 96, 48 ], (correct)
[ 0, 48 ], (correct)
[ 0, 0 ] ], (correct) // this shape is what we want
 
[ [ 96, 48 ],  (should not have this shape)
[ 96, 48 ] ]   (should not have this shape)
]

Warning message: 
< Edges of the same polygon overlap [ 0, 0 ] [ 192, 0 ] [ 96, 0 ] [ 192, 0 ]

**Comment by mandysimon88** [comment]
If you need more test cases than that, please let us know. Thank you!!!

**Comment by mandysimon88** [comment]
Here is a test case showing another facet of the overlap problem. In this case, the Martinez algorithm errors out, unable to finish calculating. This is one rectangular polygon overlapping another rectangular polygon on two edges.

[[-1883,-3],[-1883,-8.5],[-1783,-8.5],[-1783,-3],[-1883,-3]] (polygon1)
[[-1883,-25],[-1783,-25],[-1783,75],[-1883,75],[-1883,-25]] (polygon2)

Here is a screen shot illustrating what happens:

![screen shot 2016-11-22 at 9 52 32 am](https://cloud.githubusercontent.com/assets/12855692/20528262/7c09d22a-b099-11e6-80c1-b086a068885a.png)

**Comment by mandysimon88** [comment]
Here is a Test Case that gets trapped in an infinite loop, at the same point of overlapping edges:

Polygon1:
[[578,-371], [578,-491], [1778,-491], [1778,-371], [578,-371]]

Polygon2:
[[578,-971], [1964,-971], [1964,-115], [578,-115], [578,-971]]

And screenshot showing the infinite loop:
![screen shot 2016-11-24 at 4 34 13 pm](https://cloud.githubusercontent.com/assets/12855692/20610166/e700c856-b263-11e6-91ee-4e43cfde38cb.png)

**Comment by w8r** [comment]
Thanks a lot for the test cases! Sorry I cannot attend immediately, I am in a middle of a work handover process

**Comment by gap777** [comment]
@w8r any thoughts on when you might be able to fix this issue?

**Comment by w8r** [comment]
So the case from the first message is fixed, going through other examples

**Comment by w8r** [comment]
> Test case: rectangle with another rectangle, two edges overlapping:
[ [ 30, 78 ], [ 30, 30 ], [ 126, 30 ], [ 126, 78 ], [ 30, 78 ] ] (polygon1)
[ [ 30, 30 ], [ 55, 30 ], [ 55, 55 ], [ 30, 55 ], [ 30, 30 ] ] (polygon2)

**fixed**

**Comment by w8r** [comment]
> Test case: rectangle with a trapezoid, with one edge overlapping:
[ [ 0, 3.5 ], [ 0, 0 ], [ 21, 0 ], [ 21, 3.5 ], [ 0, 3.5 ] ] (rectangle)
[ [ 21, 7 ], [ 0, 7 ], [ 7, 0 ], [ 14, 0 ], [ 21, 7 ] ] (trapezoid)

**fixed**

**Comment by w8r** [comment]
> Here is a Test Case that gets trapped in an infinite loop, at the same point of overlapping edges:
 Polygon1:
[[578,-371], [578,-491], [1778,-491], [1778,-371], [578,-371]]
 Polygon2:
[[578,-971], [1964,-971], [1964,-115], [578,-115], [578,-971]]

I had to downscale it by 0.1 to see if it works, but then it does, too

**Comment by w8r** [comment]
> Here is a test case showing another facet of the overlap problem. In this case, the Martinez algorithm errors out, unable to finish calculating. This is one rectangular polygon overlapping another rectangular polygon on two edges.
[[-1883,-3],[-1883,-8.5],[-1783,-8.5],[-1783,-3],[-1883,-3]] (polygon1)
[[-1883,-25],[-1783,-25],[-1783,75],[-1883,75],[-1883,-25]] (polygon2)

This one is *fixed*

**Comment by w8r** [comment]
So the case that I had to downscale has a different problem, it's _precision_. I suggest moving that to a different issue

**Comment by dongli** [comment]
This case cause infinite loop:

```
martinez.intersection([[[-180,-16.96624016044842],[-179.99279992799933,-16.955822640501808],[-179.98919989199896,-16.94714137387956],[-179.9351993519936,-16.90026253411949],[-179.90279902799034,-16.87595498757723],[-179.81999819998205,-16.780461054732626],[-179.8523985239853,-16.691912135185817],[-179.86319863198636,-16.67975836191468],[-179.89199891998925,-16.686703375212474],[-179.92799927999286,-16.709274668430282],[-179.93879938799392,-16.716219681728077],[-180,-16.787406068030354],[-180,-16.96624016044842]]], [[[-180,0],[-180,-45],[-135,-45],[-135,0],[-180,0]]])
```

**Comment by DenisCarriere** [comment]
For anyone wondering what does coordinates look like:

Another great Fiji example.

![image](https://user-images.githubusercontent.com/550895/33010942-306ee358-cd91-11e7-8b33-9b6c540c945d.png)

![image](https://user-images.githubusercontent.com/550895/33010960-38fd4460-cd91-11e7-8a2f-5b4803473acc.png)

**Comment by w8r** [comment]
this is strange

**Comment by DenisCarriere** [comment]
Very strange things happen around Fiji... 👻

**Comment by rowanwins** [comment]
Im sure we're not the only geospatial lib that would have this problem, would be interesting to check...

**Comment by w8r** [comment]
but isn't it a date change line there? martinez is not geodetic, there has to be a workaround to introduce coordinate wrapping.

**Comment by dongli** [comment]
FYI, I am splicing world map into vector tiles, then I went into this problem. The connection with this issue is the overlapping edge.
