### ISSUE TITLE
Invalid polygon in expected result of test 'disjoint union testing'

### ISSUE THREAD

**Issue by mfogel** [w8r/martinez#61]
FYI, there's an invalid polygon in the test result [here](https://github.com/w8r/martinez/blob/v0.3.3/test/edge_cases.test.js#L217). The nesting goes 6 deep on that array of coordinates... the furthest a valid multipolygon can go is 4. The test passes, though with an invalid polygon as an expected result, I would expect the test to fail.

Looks like according to the comment there this test case is related to #47

**Comment by narrowtux** [comment]
Stumbled upon this today, if I correct the nesting (I basically treated a 3 deep nested array as a ring), the resulting geometry looks correct visually. Like in the test case, only the first ring is affected by this.

**Comment by rowanwins** [comment]
Resolved
