### ISSUE TITLE
Algorithm based on 2013 paper

### ISSUE THREAD

**Issue by erf** [w8r/martinez#72]
Hi, i've been looking into the Martinez algorithm lately and i understand this implementation is based on the 2009 paper / implementation, and was wondering why you choose it over the 2013 paper ( + implementation ) titled "A simple algorithm for Boolean operations on polygons" by the same author, which is supposed to be simpler and faster. Are you planning to implement this newer algorithm?

**Comment by sh1ng** [comment]
It's not correct. https://github.com/w8r/martinez#based-on

**Comment by erf** [comment]
The link text says "A new algorithm for computing Boolean operations on polygons", which is the old paper, but it links to the new "A simple algorithm for Boolean operations on polygons" 2013 paper. Maybe @w8r could comment on what implemenation this code is based on. Both reference implementations reside [here](http://www4.ujaen.es/~fmartin/bool_op.html).

**Comment by sh1ng** [comment]
If I remember correctly it's based on both and C++ code, but let's wait @w8r 's reply.

**Comment by w8r** [comment]
It was 2013
