### ISSUE TITLE
package.json broken

### ISSUE THREAD

**Issue by plepe** [w8r/martinez#73]
In 8b575310b17a4fe1c47bb2ea299c4ff4a3dd5888 you changed the main script in package.json from 'index.js' to 'dist/martinez.js'. Is there a specific reason why? Because my app requires your module and now I can't include it via browserify (it searches for 'require' and wants to include all files - it can't because they are already inclued, which browserify doesn't know).

If I change the 'main' in 'package.json' back to 'index.js', everything works fine.

**Comment by w8r** [comment]
It was because it was breaking with webpack. I will look at it again though. Contributions are welcome, too, cause I am a bit busy these days

**Comment by w8r** [comment]
I changed the format once again to ES6 modules. Could you please check again?

**Comment by w8r** [comment]
should be entirely fixed in `v0.4.3`

**Comment by plepe** [comment]
Sorry. I checked it and it works! :-)
