### ISSUE TITLE
martinez.union wrong response

### ISSUE THREAD

**Issue by Efimster** [w8r/martinez#90]
Hello,
martinez.union([[ [0,0],[10,0],[10,10],[0,10] ]], [[ [9,10],[21,9],[21,21],[9,21]   ]])

produces 
[[[ [0,0],[10,0],[10, 9.916666666666668],[21,9],[21,21],[9,21],[0,10] ]]]
Seems like should be 
[[[ [0,0],[10,0],[10, 9.916666666666668],[21,9],[21,21],[9,21],     **[9,10]**    [0,10] ]]]
[9,10] point is missing

This is the result produced by polygon-clipping (https://github.com/mfogel/polygon-clipping) project:
[[ [ [ 0, 0 ],
    [ 10, 0 ],
    [ 10, 9.916666666666666 ],
    [ 21, 9 ],
    [ 21, 21 ],
    [ 9, 21 ],
    [ 9, 10 ],
    [ 0, 10 ],
    [ 0, 0 ] ] ]
]

**Comment by w8r** [comment]
fixed in #111

**Comment by rowanwins** [comment]
Turns out this isn't resolved by #111 due to a slightly dodgy demo site :(

**Comment by rowanwins** [comment]
This however is resolved by using correct inputs

The arrays are missing closing coordinates (eg the first and last coord pair need to match according to the geojson spec)
